# Generated by Django 6.0.4 on 2026-04-25 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pojistenec',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pojistenec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pojistka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('zdravotni', 'Zdravotní'), ('zivotni', 'Životní'), ('automobilove', 'Automobilové'), ('majetkove', 'Majetkové'), ('cestovni', 'Cestovní'), ('urazove', 'Úrazové')], max_length=100)),
                ('nazev', models.CharField(max_length=200)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum_zacatku', models.DateField()),
                ('datum_konce', models.DateField()),
                ('aktivni', models.BooleanField(default=True)),
                ('pojistenec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pojistky', to='pojistenci.pojistenec')),
            ],
        ),
    ]
